apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME-deployment
  namespace: jenkins
  labels:
    app: APP_NAME
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          image: "IMAGE_NAME" # Replace ${BUILD_ID} with your build identifier
