apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: jenkins
  labels:
    app: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:20.10-dind
        securityContext:
          privileged: true # Required for DinD to work
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        ports:
        - containerPort: 2375 # Docker daemon port
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      volumes:
      - name: docker-graph-storage
        emptyDir: {}
